# Site settings
name: DinoZhang
email: victordinozhang@gmail.com
author: DinoZhang
url: http://dinozhang.org
### baseurl修改为项目名，如果项目是'***.github.io'，则设置为空''
baseurl: ''
motto: DinoZhang's Blog
banner: Stay hungry, stay foolish.
github: https://github.com/dinozhang/
resume_site: http://dinozhang.org/resumecards/

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: DinoZhang
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : netease
    duoshuo:
        short_name : dinozhang
    disqus :
        short_name :
